services:
  - type: web
    name: pgweb-admin
    runtime: image
    image:
      url: docker.io/sosedoff/pgweb:latest
    plan: starter
    dockerCommand: pgweb --bind=0.0.0.0 --listen=8081
    envVars:
      - key: PORT
        value: "8081"
      - key: PGWEB_DATABASE_URL
        sync: false
      - key: PGWEB_AUTH_USER
        sync: false
      - key: PGWEB_AUTH_PASS
        sync: false
